// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: examplesrv/v1/events.proto

package examplesrvv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// define the regex for a UUID once up-front
var _events_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ExampleEvent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ExampleEvent) Validate() error {
	if m == nil {
		return nil
	}

	if err := m._validateUuid(m.GetExample()); err != nil {
		return ExampleEventValidationError{
			field:  "Example",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	if v, ok := interface{}(m.GetEventAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExampleEventValidationError{
				field:  "EventAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

func (m *ExampleEvent) _validateUuid(uuid string) error {
	if matched := _events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ExampleEventValidationError is the validation error returned by
// ExampleEvent.Validate if the designated constraints aren't met.
type ExampleEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleEventValidationError) ErrorName() string { return "ExampleEventValidationError" }

// Error satisfies the builtin error interface
func (e ExampleEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleEventValidationError{}
